# Site settings
title: Rad!
name: Rad Facts
url: ""
title: ""
link: ""
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
port: 8080
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown


